version: '3'

services:
  nginx:
    container_name: tutorial-nginx
    build:
      context: ./docker-local/nginx/
    ports:
      - '80:80'
    volumes:
      - ./src/:/usr/share/nginx/html
      - ./docker-local/nginx/config/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker-local/nginx/config/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php
    networks:
      - common

  php:
    container_name: tutorial-php
    build:
      context: ./docker-local/php/
    ports:
      - '9000:9000'
    environment:
      APP_ENV: local
      DB_HOST: tutorial-mysql
      DB_NAME: tutorial
      DB_USER: root
      DB_PASS: password
    volumes:
      - ./src/:/usr/share/nginx/html
      - ./docker-local/php/config/php.ini:/etc/php.ini
      - ./docker-local/php/config/www.conf:/etc/php-fpm.d/www.conf
      - ./docker-local/php/config/php-fpm.conf:/etc/php-fpm.conf
    networks:
      - common

  mysql:
    container_name: tutorial-mysql
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: tutorial
    hostname: localhost
    networks:
      - common

  mysql-test:
    container_name: tutorial-test-mysql
    image: mysql:5.7
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: tutorial
    hostname: localhost
    networks:
      - common

  selenium:
    container_name: tutorial-selenium
    image: selenium/standalone-chrome
    ports:
      - 4444:4444
    networks:
      - common

volumes:
  tutorial-dbdata:
    driver: local

networks:
  common:
    driver: bridge
